# permissions for end users to edit resourcepresets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: presetter
    app.kubernetes.io/managed-by: kustomize
  name: resourcepreset-editor-role
rules:
- apiGroups:
  - presetter.xamma.dev
  resources:
  - resourcepresets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - presetter.xamma.dev
  resources:
  - resourcepresets/status
  verbs:
  - get
