---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - presetter.xamma.dev
  resources:
  - resourcepresets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - presetter.xamma.dev
  resources:
  - resourcepresets/finalizers
  verbs:
  - update
- apiGroups:
  - presetter.xamma.dev
  resources:
  - resourcepresets/status
  verbs:
  - get
  - patch
  - update
