apiVersion: presetter.xamma.dev/v1
kind: ResourcePreset
metadata:
  labels:
    app.kubernetes.io/name: presetter
    app.kubernetes.io/managed-by: kustomize
  name: minimal
  namespace: presets
spec:
  cpuRequests: "200m"
  cpuLimits: "500m"
  memoryRequests: "400Mi"
  memoryLimits: "1Gi"
